/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'landing-page': LandingPage;
  };
  globalsSelect: {
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: number;
  title: string;
  slug: string;
  seo: {
    title: string;
    description: string;
    ogTitle?: string | null;
    ogDescription?: string | null;
  };
  hero: {
    eyebrow?: string | null;
    heading: string;
    subheading: string;
    primaryCta?: {
      label?: string | null;
      href?: string | null;
      isExternal?: boolean | null;
    };
    secondaryCta?: {
      label?: string | null;
      href?: string | null;
      isExternal?: boolean | null;
    };
    proofBullets?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  problem: {
    eyebrow?: string | null;
    heading: string;
    copy: string;
    items?:
      | {
          title: string;
          copy: string;
          id?: string | null;
        }[]
      | null;
  };
  differentiators: {
    eyebrow?: string | null;
    heading: string;
    copy: string;
    items?:
      | {
          title: string;
          copy?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  benefits: {
    eyebrow?: string | null;
    heading: string;
    items?:
      | {
          title: string;
          copy: string;
          id?: string | null;
        }[]
      | null;
  };
  workflow: {
    eyebrow?: string | null;
    heading: string;
    introLine: string;
    steps?:
      | {
          step: string;
          title: string;
          copy: string;
          id?: string | null;
        }[]
      | null;
  };
  proof: {
    eyebrow?: string | null;
    heading: string;
    items?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  faq: {
    heading: string;
    items?:
      | {
          question: string;
          answer: string;
          openByDefault?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  contact: {
    eyebrow?: string | null;
    heading: string;
    copy: string;
    primarySubmitLabel: string;
    secondarySubmitLabel: string;
    successMessage: string;
    errorMessage: string;
  };
  footerCta: {
    eyebrow?: string | null;
    heading: string;
    copy?: string | null;
    primaryCta?: {
      label?: string | null;
      href?: string | null;
      isExternal?: boolean | null;
    };
    secondaryCta?: {
      label?: string | null;
      href?: string | null;
      isExternal?: boolean | null;
    };
  };
  contactConfig?: {
    staffEmailOverride?: string | null;
    fromNameOverride?: string | null;
    fromEmailOverride?: string | null;
    fallbackContactEmail?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subheading?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
              isExternal?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
              isExternal?: T;
            };
        proofBullets?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  problem?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        copy?: T;
        items?:
          | T
          | {
              title?: T;
              copy?: T;
              id?: T;
            };
      };
  differentiators?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        copy?: T;
        items?:
          | T
          | {
              title?: T;
              copy?: T;
              id?: T;
            };
      };
  benefits?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              copy?: T;
              id?: T;
            };
      };
  workflow?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        introLine?: T;
        steps?:
          | T
          | {
              step?: T;
              title?: T;
              copy?: T;
              id?: T;
            };
      };
  proof?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              openByDefault?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        copy?: T;
        primarySubmitLabel?: T;
        secondarySubmitLabel?: T;
        successMessage?: T;
        errorMessage?: T;
      };
  footerCta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        copy?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
              isExternal?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
              isExternal?: T;
            };
      };
  contactConfig?:
    | T
    | {
        staffEmailOverride?: T;
        fromNameOverride?: T;
        fromEmailOverride?: T;
        fallbackContactEmail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}